const actionType = {
  COVID19_INITIALISE_INFLIGHT: "COVID19_INITIALISE_INFLIGHT",
  COVID19_INITIALISE_SUCCESS: "COVID19_INITIALISE_SUCCESS",
  COVID19_INITIALISE_ERROR: "COVID19_INITIALISE_ERROR",
  COVID19_BY_COUNTRIES_INFLIGHT: "COVID19_BY_COUNTRIES_INFLIGHT",
  COVID19_BY_COUNTRIES_SUCCESS: "COVID19_BY_COUNTRIES_SUCCESS",
  COVID19_BY_COUNTRIES_ERROR: "COVID19_BY_COUNTRIES_ERROR"
};

export default actionType;
